language: rust
env:
  - TRAVIS_RUST_ARCHITECTURE=i386
  - TRAVIS_RUST_ARCHITECTURE=amd64
rust:
  - 1.21.0
  - stable
  - beta
  - nightly

before_install:
- sudo apt-get update
- sudo apt-get install -y gcc-multilib
script: ci/script.sh

branches:
  only:
    - master
