#!/bin/bash

usage() {
  echo "Usage: $(basename $0) [rust | cpp]" >&2
  exit 1
}

if [ $# = 0 ]; then
  which=rust
else
  if [ $1 = '-h' ] || [ $1 = '--help' ]; then
    usage
  fi
  which="$1"
  shift
fi

case $which in
  rust)
    exec cargo bench --manifest-path benches/Cargo.toml --features rust "$@"
    ;;
  cpp)
    exec cargo bench --manifest-path benches/Cargo.toml --features cpp "$@"
    ;;
  *)
    usage
    ;;
esac
